language: ruby
rvm:
  - 2.0.0
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
notifications:
  webhooks: https://www.buildheroes.com/api/projects/e27637d59452f18b5c97dec76d9b9f4a2e4cfcf4/builds
bundler_args: --without development
before_script:
  - mysql -e 'create database hcking_test;'
  - rake setup:config
script: "bundle exec rake db:drop db:create db:migrate ci"
cache: bundler
